#!/usr/bin/env python3
"""Pack the Panchanga's Kannada strings one byte per letter.

Kannada letters (U+0C80..U+0CFF) take three bytes in UTF-8. Here each becomes
one byte 0x80..0xFF (ASCII stays as is), which cuts the strings' flash use to
a third; kn::toUtf8() expands a string again just before it is drawn.

usage: pack_panchanga_strings.py   (reads scripts/kannada/panchanga_strings.txt,
                                    writes src/activities/tools/PanchangaStrings.h)
"""
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(ROOT, "scripts", "kannada", "panchanga_strings.txt")
OUT = os.path.join(ROOT, "src", "activities", "tools", "PanchangaStrings.h")


def pack(s):
    out = bytearray()
    for ch in s:
        cp = ord(ch)
        if cp < 0x80:
            out.append(cp)
        elif 0x0C80 <= cp <= 0x0CFF:
            out.append(0x80 + cp - 0x0C80)
        else:
            raise ValueError(f"cannot pack U+{cp:04X} in {s!r}")
    # Octal escapes never swallow a following digit (hex escapes would).
    return '"' + "".join(chr(b) if 0x20 <= b < 0x7F and chr(b) not in '"\\?' else f"\\{b:03o}" for b in out) + '"'


def main():
    sections, order, current = {}, [], None
    for raw in open(SRC, encoding="utf-8"):
        line = raw.rstrip("\n")
        if not line or line.startswith("#"):
            continue
        if line.startswith("["):
            name = line[1:line.index("]")]
            current = (name, line.endswith("single"))
            sections[current] = []
            order.append(current)
            continue
        sections[current].append("" if line == "(empty)" else line)
    lines = ["#pragma once", "", "#include <cstddef>", "#include <cstdint>", "",
             "// Generated by scripts/kannada/pack_panchanga_strings.py from",
             "// scripts/kannada/panchanga_strings.txt. Do not edit.",
             "//",
             "// Kannada Panchanga strings, one byte per letter: 0x80 + (codepoint - U+0C80)",
             "// for Kannada, ASCII unchanged. kn::toUtf8() expands them for drawing with",
             "// the SD card Kannada font (KannadaText.h).",
             "namespace kn {", ""]
    for (name, single) in order:
        items = sections[(name, single)]
        if name == "Label enum":
            lines.append("enum class Label : uint8_t {")
            lines += [f"  {n}," for n in items]
            lines += ["};", ""]
        elif single:
            lines += [f"inline constexpr const char* {name} = {pack(items[0])};", ""]
        else:
            lines.append(f"inline constexpr const char* {name}[] = {{")
            lines += [f"    {pack(s)}," for s in items]
            lines += ["};", ""]
    lines += [
        "// Expands a packed string into out (UTF-8, always terminated); returns out.",
        "inline const char* toUtf8(const char* packed, char* out, const size_t cap) {",
        "  size_t n = 0;",
        "  for (const char* p = packed; *p != '\\0' && n + 4 < cap; ++p) {",
        "    const auto b = static_cast<uint8_t>(*p);",
        "    if (b < 0x80) {",
        "      out[n++] = static_cast<char>(b);",
        "      continue;",
        "    }",
        "    const uint32_t cp = 0x0C80u + (b - 0x80u);  // three UTF-8 bytes",
        "    out[n++] = static_cast<char>(0xE0 | (cp >> 12));",
        "    out[n++] = static_cast<char>(0x80 | ((cp >> 6) & 0x3F));",
        "    out[n++] = static_cast<char>(0x80 | (cp & 0x3F));",
        "  }",
        "  out[n] = '\\0';",
        "  return out;",
        "}",
        "",
        "}  // namespace kn", ""]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
